export const resumeUrl = "https://drive.google.com/drive/folders/1h7oU7hN-NM4L60W2YLsIi19tlULZEre7";

export const projects = [
  {
    slug: "shop-lc-checkout",
    number: "01",
    category: "Product design",
    period: "2020 to 2024",
    client: "Shop LC",
    title: "A clearer path to checkout",
    description: "A web and mobile UX overhaul that made the shopping journey easier to understand, from the first product interaction to a more confident checkout.",
    tags: ["UX and UI", "Research", "Accessibility"],
    tone: "blue",
    feature: "Shop with confidence",
    detail: "I partnered with developers, stakeholders, and conversion teams to simplify promotional experiences and checkout paths across web and mobile. The work included research, UX and UI overhauls, structured platform testing, and accessible interface design aligned with ADA and WCAG standards.",
    outcome: "A clearer, more inclusive purchase journey built around user confidence.",
  },
  {
    slug: "angara-creative-workflows",
    number: "02",
    category: "Creative systems",
    period: "2024 to 2026",
    client: "Angara Ecommerce",
    title: "Making good ideas move faster",
    description: "An AI-assisted creative workflow for turning early concepts into polished campaign assets without losing the human point of view.",
    tags: ["AI workflows", "Art direction", "Systems"],
    tone: "lime",
    feature: "A faster first draft",
    detail: "I combined traditional design principles with generative tools to accelerate asset ideation and concept visualization. The focus was on building a repeatable process that still respected exact business requirements and a high bar for visual quality.",
    outcome: "A more consistent creative pipeline from first idea to finished asset.",
  },
  {
    slug: "crystaltech-campaigns",
    number: "03",
    category: "Visual design",
    period: "2018 to 2020",
    client: "Crystaltech Esolutions",
    title: "Design that earns attention",
    description: "Social campaigns, e-commerce landing pages, and seasonal systems with a stronger visual point of view.",
    tags: ["Visual design", "Campaigns", "E-commerce"],
    tone: "lavender",
    feature: "Make it memorable",
    detail: "I designed targeted marketing graphics, promotional assets, e-commerce landing pages, and seasonal banner campaigns across digital channels. Each piece was shaped to communicate clearly while creating a more consistent brand presence.",
    outcome: "A cohesive set of campaign touchpoints built for digital engagement.",
  },
] as const;
