export const resumeUrl = "https://drive.google.com/file/d/1__8G6ZHDYltuZUdplqrhPwu8yfFoEAL1/view";

export const projects = [
  {
    slug: "shop-lc-checkout",
    number: "01",
    category: "Womens fashion",
    period: "2020 to 2024",
    client: "Shop LC",
    title: "A clearer path through womens fashion",
    description: "A web and mobile shopping experience for womens fashion that made product discovery, outfit exploration, and checkout easier to understand.",
    tags: ["Womens fashion", "UX and UI", "Accessibility"],
    tone: "blue",
    feature: "Shop fashion with confidence",
    image: "https://cdn.builder.io/api/v1/image/assets%2Fa98f46cecf9b46458c97a073c7e06eda%2Fb05eab8402914b65b88c91a9d9214411?format=webp&width=800&height=1200",
    detail: "I partnered with developers, stakeholders, and conversion teams to simplify womens fashion shopping experiences across web and mobile. The work included product discovery, UX and UI improvements, structured platform testing, and accessible interface design aligned with ADA and WCAG standards.",
    outcome: "A clearer, more inclusive fashion shopping journey built around user confidence.",
  },
  {
    slug: "angara-creative-workflows",
    number: "02",
    category: "Creative systems",
    period: "2024 to 2026",
    client: "Angara Ecommerce",
    title: "Making good ideas move faster",
    description: "An AI-assisted creative workflow for turning early concepts into polished campaign assets without losing the human point of view.",
    tags: ["AI workflows", "Art direction", "Systems"],
    tone: "lime",
    feature: "A faster first draft",
    image: "https://cdn.builder.io/api/v1/image/assets%2Fa98f46cecf9b46458c97a073c7e06eda%2Ff93ba5441c044ddea83ec8829b18ebba?format=webp&width=800&height=1200",
    detail: "I combined traditional design principles with generative tools to accelerate asset ideation and concept visualization. The focus was on building a repeatable process that still respected exact business requirements and a high bar for visual quality.",
    outcome: "A more consistent creative pipeline from first idea to finished asset.",
  },
  {
    slug: "cosmicchat-aesthetics-usability",
    number: "03",
    category: "UX case study",
    period: "Independent project",
    client: "CosmicChat",
    title: "CosmicChat: Balancing Aesthetics & Usability",
    description: "A UX case study on transforming a design-led app into a user-centered experience, increasing task success rates from 42% to 89%.",
    tags: ["UX research", "Usability", "UI design"],
    tone: "lavender",
    feature: "A clearer conversation flow",
    visual: "cosmic-after",
    externalUrl: "https://tonyshh3.github.io/cosmictech-case-study/",
    detail: "A UX case study focused on transforming a design-led chat experience into a clearer, more user-centered product.",
    outcome: "Task success increased from 42% to 89% through clearer navigation and interaction patterns.",
  },
] as const;
